############### NETWORKS ###############
networks:
    subnet:
        driver: bridge

############### SERVICES ###############
include:
    # --> database services
    - compose/mariadb.yml
    - compose/pgsqldb.yml
    - compose/ollamasvc.yml

    # --> infrastructure
    - compose/traefik.yml

    # --> Web applications
    - compose/wordpress.yml
    - compose/gitea.yml
    - compose/openmaic.yml